spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: localhost
      port: ${DB_PORT}
      database: ${DB_NAME}
      auto-index-creation: true

    redis:
      host: localhost
      port: ${REDIS_PORT}



