spring:
  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: FeedSystem
#      auto-index-creation: true

    redis:
      host: localhost
      port: 6379

# Actuator endpoints for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info # expose only health and info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger




